target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'MultiPlatformLibrary', :path => '../MultiPlatformLibrary'
  pod 'mokoMvvmFlowSwiftUI', :podspec => 'https://raw.githubusercontent.com/icerockdev/moko-mvvm/release/0.14.0/mokoMvvmFlowSwiftUI.podspec'
end